### ISSUE TITLE
Will not run on < PHP 7.0

### ISSUE THREAD

**Issue by supergrecko** [plumthedev/personalized#10]
Because parameter type hinting and parameter type hinting was released with PHP 7 the code will fail on anything below 7.0

**Comment by plumthedev** [comment]
thanks for the feedback, that's true so i resolve this issue in two ways. Change in readme requirements or add phpDoc blocks to support anything below 7.0

**Comment by supergrecko** [comment]
I believe you should change the README requirements because PHP 5.x is deprecated and anybody should use PHP 7+ anyways.

**Comment by plumthedev** [comment]
@supergrecko thanks for good tip, in next commit I change this and close this issue, I encourage to follow me and star this library!
