### ISSUE TITLE
Add implementation of SetInterval and SetTimeout to Data 

### ISSUE THREAD

**Issue by plumthedev** [plumthedev/personalized#13]

**Comment by plumthedev** [comment]
and SetTimeout too

**Comment by supergrecko** [comment]
How are you planning to write async php? ReactPHP?

**Comment by plumthedev** [comment]
simply sleep function implementation 😃

**Comment by plumthedev** [comment]
I must add implementation of SetInterval and SetTimeout like in JavaScript

**Comment by supergrecko** [comment]
You know PHP's sleep() blocks the entire IO loop and sleeps the entire program right?

**Comment by plumthedev** [comment]
Some of problem now are solved but there are few new.

As @supergrecko write, when I call _sleep()_ then entire program go sleep, because PHP is not async. 
This issue is fixed but no solved, I must find better solution for this.

**Comment by plumthedev** [comment]
entire library in the assumption is runned from command line, so in my opinion I can use sleep because only running script is going sleep not entire server
